### PR TITLE
Make cache and update yum repository

### PR DESCRIPTION
**Pull request by chibiegg**

### CODE REVIEW

**Comment by nemomasa** [comment]
Can one of the admins verify this patch?

**Comment by chibiegg** [comment]
As usual it seems that Mr. @zembutsu will test, review and merge.

**Comment by chibiegg** [comment]
Sorry, this is not the cause. Close once.

**Comment by chibiegg** [comment]
Note: [0013669: can't install nodejs on centos7 - CentOS Bug Tracker](https://bugs.centos.org/view.php?id=13669&nbn=1)

**Pull request closed without merging**
